

export const AD_VALUES: string[] = [
    'First Name',
    'Middle Name / Initials',
    'Last Name',
    'Logon Name',
    'Logon Name (Pre Windows 2000)',
    'Display Name',
    'Full Name',
    'Description',
    'Office',
    'Telephone Number',
    'Email',
    'Web Page',
    'Password',
    'Street',
    'PO Box',
    'City',
    'State/Province',
    'Zip/Postal Code',
    'Country',
    'Country 2 Digit Code - eg. US',
    'Country code -eg. for US country code is 840',
    'Group',
    'Account Expires (use same date format as server)',
    'User Account Control',
    'Profile Path',
    'Login Script',
    'Home Folder',
    'Home Drive',
    'Log on to',
    'Home',
    'Pager',
    'Mobile',
    'Fax',
    'IP Phone',
    'Notes',
    'Title',
    'Department',
    'Company',
    'Manager',
    'Mail Alias',
    'Simple Display Name',
    'Hide from Exchange address lists',
    'Sending Message Size (KB)',
    'Receiving Message Size (KB)',
    'Accept messages from Authenticated Users only',
    'Reject Messages From',
    'Accept Messages From',
    'Send on Behalf',
    'Forward To',
    'Deliver and Redirect',
    'Reciepient Limits',
    'Use mailbox store defaults',
    'Issue Warning at (KB)',
    'Prohibit Send at (KB)',
    'Prohibit Send and receive at (KB)',
    'Do not permanaently delete messages until the store has been backed up',
    'keep deleted items for (days)',
    'Outlook Mobile Access',
    'Outlook Web Access',
    'Allow Terminal Server Logon',
    'Terminal Services Profile Path',
    'Terminal Services Home Directory',
    'Terminal Services Home Drive',
    'Start the following program at logon',
    'Starting Program file name',
    'Start in',
    'Connect client drive at logon',
    'Connect client printer at logon',
    'Default to main client printer',
    'End disconnected session',
    'Active Session limit',
    'Idle session limit',
    'When session limit reached or connection broken',
    'Allow reconnection',
    'Remote Control',
    'Protect accidental deletion',
    'Manager can update members',
    'Primary Group ID',
    'Administrative Group',
    'Exchange Server Name',
    'Managed By',
    'Target Address',
    'Proxy-Addresses',
    'Automatically Update Email-address based on Recipient Policy',
    'Office 365 Group Membership',
    'Enable Litigation Hold for Mailbox',
    'Litigation Hold Duration for Exchange Mailbox',
    'Enable in-place Archive for User Mailbox',
    'Archive Name for User\'s Mailbox Archive',
    'User Principal Name of Office 365 user account'
];
